page_list = {
    "登入": ['', '//*[@id="lang"]', 0],
    "主頁": ['/index', '/html/body/div[3]/div/div[4]/div[1]/div/div/h4/span', 0],
    "帳務-遊戲績效": ['/Accounting/game_performance', '/html/body/div[4]/div/div[4]/div[1]/div/div/h4/span', 0],
    "帳務-遊戲績效(小時)": ['/game_performance', '/html/body/div[4]/div/div[4]/div[1]/div/div/h4/span', 0],
    "帳務-遊戲績效(機器人)": ['/Accounting/robot_game_performance',
                     '/html/body/div[4]/div/div[4]/div[1]/div/div/h4/span', 0],
    "帳務-彩金績效": ['/Accounting/jackpot_performance', '/html/body/div[4]/div/div[4]/div[1]/div/div/h4/span', 0],
    "帳務-刮刮樂績效": ['/Accounting/scratch_performance', '//*[@id="sh_btn"]', 0],
    "帳務-遊戲排行": ['/Accounting/game_rank', '//*[@id="sh_btn"]', 0],
    "帳務-錯誤帳務": ['/Accounting/error_accounts', '/html/body/div[3]/div/div[4]/div[1]/div/div/h4/span', 0],
    "帳務-補單帳務": ['/Accounting/reaccounting', '//*[@id="DataTables_Table_0"]', 0],
    "玩家-玩家資訊-玩家資訊": ['/Player/player_info', '//*[@id="black_list"]/div/legend', 0],
    "玩家-玩家資訊-玩家帳戶": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[2]/a',
                     '//*[@id="player_account"]/div/legend', 1],
    "玩家-玩家查詢": ['/Player/player_query', '//*[@id="sh_btn"]', 0],
    "玩家-玩家狀態": ['/Player/player_status', '//*[@id="recharge_btn"]', 0],
    "玩家-Ban玩家": ['/Player/player_ban', '//*[@id="ban_btn"]', 0],
    "玩家-遊戲紀錄": ['/Player/game_history', '/html/body/div[4]/div/div[4]/div[1]/div/div/h4/span', 0],
    "玩家-交易紀錄": ['/Player/transaction', '/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div[2]/div[8]/label', 0],
    "玩家-熱門遊戲": ['/Accounting/hot_games', '//*[@id="export"]', 0],
    "玩家-遊戲留存率": ['/Player/game_retention', '/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div[2]/div[8]', 0],
    "玩家-玩家遊戲存檔": ['/Player/saved_game', '//*[@id="sh_btn"]', 0],
    "玩家-裝置統計": ['/Player/device_statistics', '/html/body/div[3]/div/div[4]/div[2]/div[2]/div[1]', 0],
    "玩家-錢包轉換": ['/Player/wallet_switch', '//*[@id="batch_btn"]', 0],
    "玩家-錢包查詢": ['/Player/wallet_search', '/html/body/div[4]/div/div[4]/div[1]/div/div/h4/span', 0],
    "玩家-補錢結果查詢": ['/Player/wallet_change_query', '//*[@id="DataTables_Table_0"]', 0],
    "彩金-彩金(中獎名單)": ['/Jackpot/winner_list', '//*[@id="search_time_type"]', 0],
    "彩金-群組設定": ['/Jackpot/group_setting', '//*[@id="reset"]', 0],
    "彩金-代理商獎池設定": ['/Jackpot/host_pool_setting', '//*[@id="prize_pool_code"]', 0],
    "彩金-彩金設定": ['/Jackpot/setting', '//*[@id="reset"]', 0],
    "彩金-獎池範圍佇列": ['/Jackpot/limit_queue', '//*[@id="agent_setting_btn"]', 0],
    "活動-活動設定(刮刮樂設定)": ['/Scratch/setting', '//*[@id="prob_btn"]', 0],
    "活動-群組設定": ['/Scratch/scratch_group_setting', '//*[@id="black_list"]/div/div/div/div[2]/table', 0],
    "活動-玩家查詢": ['/Scratch/scratch_player_query', '/html/body/div[4]/div/div[4]/div[2]/div[2]/div[1]', 0],
    "活動-中獎名單": ['/Scratch/scratch_hit_list', '/html/body/div[4]/div/div[4]/div[2]/div[2]/div[1]/div/div/h1', 0],
    "活動-中獎績效": ['/Scratch/hit_performance',
                '/html/body/div[4]/div/div[4]/div[2]/div[2]/div[3]/div/div[2]/div/div/div[2]/table', 0],
    "活動-活動模組": ['/Scratch/Event_module_index', '/html/body/div[4]/div/div[4]/div[2]/div[2]/div/div', 0],
    "活動-活動派彩": ['/Scratch/Event_payout_index', '//*[@id="game_type"]', 0],
    "活動-排行榜活動設定": ['/Scratch/Event_list_setting', '//*[@id="bonusLimit_btn"]', 0],
    "活動-排行榜中獎名單": ['/Scratch/Event_listofwinners', '//*[@id="player"]', 0],
    "大廳-遊戲設定": ['/Lobby/game_setting', '//*[@id="agent_attr"]', 0],
    "大廳-玩家查詢-玩家資訊": ['/Lobby/player_query', '//*[@id="agent_attr"]', 0],
    "大廳-玩家查詢-玩家升級": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[2]',
                     '//*[@id="player_up_level"]/div[1]/div/div/div[2]/div[1]/div/button[1]', 1],
    "大廳-玩家查詢-玩家徽章收集": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[3]',
                       '//*[@id="player_exp_agent"]', 1],
    "大廳-玩家查詢-玩家徽章兌換": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[4]',
                       '//*[@id="player_exp_sh_btn"]', 1],
    "大廳-遊戲類別-今日精選": ['/Lobby/game_categorys', '//*[@id="special_btn"]', 0],
    "大廳-遊戲類別-遊戲類別": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[2]',
                     '//*[@id="game_category"]/div/div/div/div/div[2]/div', 1],
    "大廳-信件發送": ['/Lobby/mail_send', '//*[@id="agentSelectAll"]', 0],
    "大廳-金幣設定": ['/Lobby/coin_setting', '//*[@id="player_single_btn"]', 0],
    "大廳-金幣帳務": ['/Lobby/coin_accounting', '//*[@id="export"]', 0],
    "配置-我的控制台": ['/Configuration/my_admin', '//*[@id="gp01"]', 0],
    "配置-代理商管理": ['/Configuration/agent_managemen',
                 '/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div[2]/div[4]/div/button', 0],
    "配置-API 管理-API 申請管理": ['/Configuration/api_management', '//*[@id="status"]', 0],
    "配置-API 管理-使用者管理": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[2]',
                        '//*[@id="user_status"]', 1],
    "配置-API 管理-註冊金鑰管理": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[3]',
                         '//*[@id="k_Add"]', 1],
    "配置-帳號管理": ['/Configuration/id_management', '//*[@id="admin_id"]', 0],
    "配置-遊戲配置-老虎機設定": ['/Configuration/game_config', '//*[@id="agent_attr"]', 0],
    "配置-遊戲配置-魚機設定": ['/Configuration/game_config?page=fish', '//*[@id="DataTables_Table_0"]', 0],
    "配置-遊戲配置-百家樂設定": ['/Configuration/game_config?page=bcrt', '//*[@id="agent_attr"]', 0],
    "配置-遊戲配置-拉密設定": ['/Configuration/game_config?page=dummy', '//*[@id="game_server_url"]', 0],
    "配置-遊戲配置-棋牌設定": ['/Configuration/game_config?page=pok_deng', '//*[@id="agent_attr"]', 0],
    "配置-遊戲配置-街機設定": ['/Configuration/game_config?page=arcade', '//*[@id="agent_attr"]', 0],
    "配置-遊戲配置-遊戲管理": ['/Configuration/game_config?page=game', '//*[@id="server"]', 0],
    "配置-遊戲配置-拉密遊戲管理": ['/Configuration/game_config?page=dummy_game_config', '//*[@id="copy_to_server"]', 0],
    "配置-大廳排序": ['/Configuration/game_sort', '//*[@id="example_download"]', 0],
    "配置-權限設定-功能權限": ['/Configuration/authority_setting', '//*[@id="Add"]', 0],
    "配置-權限設定-功能使用者": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[2]',
                      '//*[@id="function_user"]/div/div/div/div[2]/div/table', 1],
    "配置-權限設定-代理商權限": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[3]',
                      '//*[@id="agent_authority_setting"]/div/div/div/div[2]/div/table', 1],
    "配置-系統設定-主機資訊": ['/Configuration/system_setting', '//*[@id="DataTables_Table_0"]', 0],
    "配置-系統設定-網域資訊": ['/html/body/div[4]/div/div[4]/div[2]/div[2]/div/div/div/ul/li[2]',
                     '//*[@id="domain_info_setting"]/div/div/div/div[2]/div/table', 1],
    "配置-系統設定-資料庫設定": ['/html/body/div[4]/div/div[4]/div[2]/div[2]/div/div/div/ul/li[3]',
                      '//*[@id="server_setting"]/div/div/div/div[2]/div/table', 1],
    "配置-系統設定-白名單": ['/html/body/div[4]/div/div[4]/div[2]/div[2]/div/div/div/ul/li[4]', '//*[@id="agent_attr"]', 1],
    "配置-系統設定-地區白名單": ['/html/body/div[4]/div/div[4]/div[2]/div[2]/div/div/div/ul/li[5]',
                      '//*[@id="attributes"]', 1],
    "配置-系統日誌-系統日誌": ['/Configuration/system_Log', '//*[@id="DataTables_Table_0"]', 0],
    "配置-系統日誌-登入日誌": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[2]',
                     '//*[@id="DataTables_Table_1"]', 1],
    "配置-系統日誌-API 日誌": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[3]',
                       '//*[@id="DataTables_Table_2"]', 1],
    "配置-系統日誌-伺服器日誌": ['/html/body/div[4]/div/div[4]/div[2]/div[1]/div/div/div/ul/li[4]',
                      '//*[@id="DataTables_Table_3"]', 1],
    "登出": ['/logout', '/html/body/div[3]/div/div/div/div/div', 0]
 }
